name: Feature Request
description: Idee für eine neue Funktion.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Welches Problem löst das?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Gewünschtes Verhalten
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
    validations:
      required: false
